[package]
name = "odilia-input"
version = "0.0.1"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>"]
description = "Input subsystem for the Odilia screen reader."
license = "gpl-3" # Not gpl-3-or-later
readme = "README.md"
repository = "https://github.com/odilia-app/odilia"
homepage = "https://odilia.app"
keywords = ["accessibility", "a11y", "input", "evdev", "linux"]
categories = ["accessibility"]
edition = "2021"
publish = false

[dependencies]
evdev = { version = "0.11.4", features = ["tokio"] }
futures = "0.3.21"
futures-core = "0.3.21"
inotify = "0.10.0"
tokio = { version = "1.16.1", features = ["fs", "rt", "sync"] }
tracing = "0.1.30"

[features]
